
// OS relevante Headerfiles
#define NOMINMAX
#include <omp.h>
#include <Windows.h>

// C Headerfiles
#include <cmath>
#include <ctime>
#include <cstdlib>

// STL Headerfiles
#include <algorithm>
#include <array>
#include <fstream>
#include <functional>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <queue>
#include <limits>
#include <random>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <vector>

// Eigene Mathelib
#include "linAlg.h"

// Headerfiles aus x-ray
#include "aabb.h"
#include "accelerator.h"
#include "accelrenderer.h"
#include "adprenderer.h"
#include "ambient.h"
#include "arealight.h"
#include "assimpmaterial.h"
#include "assimpmeshtriangle.h"
#include "bih.h"
#include "boxedgaussfilter.h"
#include "boxfilter.h"
#include "boxfilter2.h"
#include "boxfilter3.h"
#include "brdf.h"
#include "btdf.h"
#include "bv.h"
#include "bvhwrapper.h"
#include "camera.h"
#include "constants.h"
#include "debugmaterial.h"
#include "debugsphere.h"
#include "dielectric.h"
#include "directional.h"
#include "disc.h"
#include "displayinfo.h"
#include "emissive.h"
#include "environmentlight.h"
#include "film.h"
#include "filter.h"
#include "flatmeshtriangle.h"
#include "fresnelreflector.h"
#include "fresneltransmitter.h"
#include "garbagebin.h"
#include "gaussfilter.h"
#include "glossyspecular.h"
#include "guicomm.h"
#include "hammersleys.h"
#include "hemispheres.h"
#include "imageio.h"
#include "imagetex.h"
#include "instance.h"
#include "kdtree.h"
#include "lambertian.h"
#include "lambertiantex.h"
#include "light.h"
#include "lightshape.h"
#include "material.h"
#include "matte.h"
#include "mattetex.h"
#include "mesh.h"
#include "meshparser.h"
#include "meshtriangle.h"
#include "midpoints.h"
#include "mirror.h"
#include "mitchellfilter.h"
#include "mutexedrng.h"
#include "noaccel.h"
#include "nofilter.h"
#include "norenderer.h"
#include "normalmap.h"
#include "obj.h"
#include "options.h"
#include "orthocamera.h"
#include "parser.h"
#include "pathtracer.h"
#include "perfectspecular.h"
#include "perfecttransmitter.h"
#include "phong.h"
#include "photon.h"
#include "photonpool.h"
#include "photonrenderer.h"
#include "pinhole.h"
#include "plane.h"
#include "pointlight.h"
#include "ppm.h"
#include "prendfilter.h"
#include "progressbar.h"
#include "randoms.h"
#include "ray.h"
#include "realisticmirror.h"
#include "rect.h"
#include "refprobability.h"
#include "renderer.h"
#include "samplestorage.h"
#include "scene.h"
#include "sceneloader.h"
#include "settingloader.h"
#include "settings.h"
#include "shape.h"
#include "simplefilm.h"
#include "simplerenderer.h"
#include "smoothmeshtriangle.h"
#include "spectrum.h"
#include "specular.h"
#include "speculartex.h"
#include "sphere.h"
#include "stratifieds.h"
#include "stringutils.h"
#include "texture.h"
#include "transparent.h"
#include "triangle.h"
#include "unitsampler.h"
#include "viewplanesampler.h"
#include "world.h"
#include "x-ray.h"